### ISSUE TITLE
Nginx allocates directive-name from conf->pool

### ISSUE THREAD

**Issue by sambhav2411** [freenginx/nginx#5] opened 2024-10-24 23:01 UTC
During conf file parsing, directive names are allocated from the cycle pool (cf->pool).
It makes sense to allocate the directive's argument/(s) from a pool that persists for the lifetime of the cycle, as modules generally don't clone these arguments but store them directly in their respective confs.
However, It would be more efficient to allocate the directive name itself from a temporary pool, one that only lives during the configuration parsing process. Since the directive name is only needed for comparison against the module's command array, it seems unnecessary for it to persist for the entire cycle.

There is one catch here, if any directive has set it's custom handler (cf->handler), then the first argument in cf->args cannot be assumed to be the directive-name so, it should be stored on the cycle pool only. We can exclude this case.

This approach brings memory benefits when Nginx loads potentially tons of conf files.

**Comment by mdounin** [comment] 2024-10-25 22:15
> Since the directive name is only needed for comparison against the module's command array, it seems unnecessary for it to persist for the entire cycle.

While the directive name is usually used only for comparison, that's not a requirement. Blocks with custom configuration handlers, such as `map{}` and `geo{}`, is the most obvious case when the first argument can be used at runtime. Still, a normal directive can remember its name and use it at runtime as well - similarly to what `ngx_http_access_rule()` does to distinguish different rules, but assuming this distinction is postponed till runtime.  Or, for example, when the actual directive name is used for logging.

While allocation rules can be changed to something more complex, with the first argument (directive name) being from the temporary pool by default, this looks like a quite risky change with uncertain benefits. At the very least, the memory benefits in some real configurations need to be demonstrated. If you have some example configurations in mind, please provide details.

Note well that when memory used for configuration parsing can be an issue, this is usually resolved by using temporary pool for the particular block parsing - such as used in the geo module, see `ngx_http_geo_block()` for an example.

**Comment by sambhav2411** [comment] 2024-10-26 00:51
Hey Maxim,

Thanks for your comment. 
We tested this change in pre-production with around 2M server blocks, the Nginx master process memory reduced by around 6% by deploying this change. The initial memory taken by Nginx (one worker process) was around 230 GB, with the above change, the memory reduced by 14 GB. 

We can exclude the case when there is a custom configuration handler registered, as the first argument in the `args` array, cannot be assumed to be the directive name in such cases.

I agree this might be risky. But, atleast simple directives with standard configuration handler can get the directive name from `cmd->name.data` (inside their directive `set` function) also, if they choose to store it till runtime.  

I am proposing a code snippet something like this in `ngx_conf_file.c`. We might guard this block under some flag.
```c
if (cf->handler == NULL && cf->args->nelts == 1) {
     word->data = ngx_pnalloc(cf->temp_pool, b->pos - 1 - start + 1);
 } else {
     word->data = ngx_pnalloc(cf->pool, b->pos - 1 - start + 1);
}
```

**Comment by mdounin** [comment] 2024-10-26 22:12
> We tested this change in pre-production with around 2M server blocks, the Nginx master process memory reduced by around 6% by deploying this change. The initial memory taken by Nginx (one worker process) was around 230 GB, with the above change, the memory reduced by 14 GB.

Is it some real configuration, or just a constructed one for testing this specific change? Also, could you please provide some snippets to better understand configuration being tested?

**Comment by sambhav2411** [comment] 2024-10-29 18:21
Hey @mdounin ,

Unfortunately, I won't be able to share the config on which 6% memory benefits were seen. The memory benefits depend on the number and length of directives in the config. I tried to see the memory benefits with a constructed config.

```
server {
    include common-server-settings.conf;
    listen 443;
    listen [::]:443 ssl;
    server_name kedod7623n.example.com;
    ssl_certificate default.crt;
    ssl_certificate_key default.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384";
    root /var/www/kedod7623n.example.com;
    index index.html;
 
    location / {
        include common-location-settings.conf;
        try_files $uri $uri/ =404;
    }
}
```

I repeated this config 500k times using the below script[
[gen_config.txt](https://github.com/user-attachments/files/17561369/gen_config.txt)
](url)

However, I do not see much memory benefits from running this with/without the change. I see memory benefit of 28.3 MB.

Without change:
```
root@myvm:/home/sambhav/nginx#
free -b
               total        used        free      shared  buff/cache   available
Mem:     135001239552 11647315968 120327499776     4280320  3026423808 122193510400
Swap:              0           0           0
```

With change:
```
root@myvm:/home/sambhav/nginx# free -b
               total        used        free      shared  buff/cache   available
Mem:     135001239552 11676991488 120297648128     4280320  3026599936 122163834880
Swap:              0           0           0
```

However, I added malloc_trim(0) call after the pool was destroyed in both the cases.

**Comment by mdounin** [comment] 2024-10-29 22:26
Given `include` being used in the configuration and relevant files not provided, it is not possible to reproduce the exact configuration you are testing. Still, moving common `ssl_protocols`, `ssl_ciphers`, and `index` directives to the `http{}` level will result in more than 100 bytes saved per `server{}`, and therefore more than 50MB saved in the test configuration with 500k servers. That is, trivial changes to the configuration make it possible to save more memory than the proposed unsafe code modifications.

Note well that for configuration with lots of server{} blocks another possible improvement to consider would be to use less server blocks. In particular, using a single server and variables to provide domain-specific settings, such as root path. This approach might not be trivial for SSL-enabled servers though, as it needs either dynamic certificate loading or using certificates for multiple domains. Still, this approach will likely result in much smaller memory footprint, not at all possible with other optimizations.

Overall, I don't think that trying to not allocate directive names worth the effort. Even if successfully implemented, potential benefits are quite limited, and other optimization strategies are likely to be able to save much more memory. Thanks for the suggestion.

**Closed as completed** 2024-11-05 04:23 UTC
Labels: enhancement
